dist: xenial
language: python
jobs:
  include:
  - python: "2.6"
    dist: trusty
  - python: "2.7"
  allow_failures:
  - python: "2.6"
    dist: trusty
addons:
  apt:
    packages:
    - unicode-data
    - flex
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then if_rstlint=:; fi
install:
- pip install pydiatra $pyflakes
- $if_rstlint pip install restructuredtext-lint pygments
script:
- make
- make test
- make install PREFIX=~/.local
- python -m pydiatra .
- pyflakes .
- $if_rstlint restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
