name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
        cc:
        - gcc
        - clang
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: install deps
      run:
        sudo apt-get install flex unicode-data
    - name: check C compiler version
      run:
        ${{matrix.cc}} --version
    - name: build the executable
      run:
        make CC=${{matrix.cc}}
    - name: run tests
      run:
        make test
    - name: install the executable
      run:
        make install PREFIX=~/.local
    - name: clean up
      run:
        make clean
    - name: run as-installed tests
      run:
        make test-installed
    - name: run pydiatra
      run: |
        python -m pip install --user pydiatra
        python -m pydiatra .
    - name: run pyflakes
      run: |
        python -m pip install --user pyflakes
        python -m pyflakes .
    - name: check README syntax
      run: |
        python -m pip install pygments restructuredtext-lint
        rst-lint --level=info --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
